version: "3.8"

services:
  postgres:
    image: postgres:17
    container_name: postgreSQL
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1911
      POSTGRES_DB: db_transacoes
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d db_transacoes" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: transacao_simplificada
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/db_transacoes
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1911
    ports:
      - "8080:8080"

volumes:
  postgres_data: